name: renovate-config

"on":
  push:
    paths:
      - 'default.json'
    branches:
      - main
  pull_request:
    paths:
      - 'default.json'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7
      - run: npx --package renovate -c 'renovate-config-validator'
      - run: npx --package renovate -c 'renovate-config-validator default.json'